# Generated by Django 4.2.10 on 2024-03-14 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="blog",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
    ]
